export const TRUTHLENS_SOULBOUND_ABI = [
  "constructor(string name, string symbol, address initialAdmin)",
  "error SoulboundTokenCannotBeTransferred()",
  "error CredentialAlreadyExists(string credentialId)",
  "error CredentialHashAlreadyUsed(bytes32 hash)",
  "error CredentialNotFound()",
  "error CredentialAlreadyRevoked()",
  "error InvalidRecipientAddress()",
  "error EmptyCredentialData()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "event CredentialIssued(uint256 indexed tokenId, string indexed credentialId, address indexed recipient, bytes32 credentialHash, string ipfsCID, address issuer, uint256 issuedAt)",
  "event CredentialRevoked(uint256 indexed tokenId, string indexed credentialId, address indexed revoker, string reason, uint256 revokedAt)",
  "event Locked(uint256 tokenId)",
  "event Unlocked(uint256 tokenId)",
  "function locked(uint256 tokenId) external view returns (bool)",
  "function issueCredential(address recipient, string calldata credentialId, bytes32 credentialHash, string calldata ipfsCID) external returns (uint256)",
  "function revokeCredential(uint256 tokenId, string calldata reason) external",
  "function getCredentialByTokenId(uint256 tokenId) external view returns (tuple(uint256 tokenId, string credentialId, bytes32 credentialHash, string ipfsCID, address recipient, address issuer, uint256 issuedAt, uint8 status, uint256 revokedAt))",
  "function getCredentialById(string calldata credentialId) external view returns (tuple(uint256 tokenId, string credentialId, bytes32 credentialHash, string ipfsCID, address recipient, address issuer, uint256 issuedAt, uint8 status, uint256 revokedAt))",
  "function getCredentialsByRecipient(address recipient) external view returns (uint256[] memory)",
  "function verifyCredential(string calldata credentialId, bytes32 expectedHash) external view returns (bool isValid, bool isRevoked, address recipient, string memory ipfsCID, uint256 issuedAt)",
  "function name() external view returns (string)",
  "function symbol() external view returns (string)",
  "function ownerOf(uint256 tokenId) external view returns (address)",
  "function balanceOf(address owner) external view returns (uint256)",
  "function hasRole(bytes32 role, address account) external view returns (bool)",
  "function ISSUER_ROLE() external view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() external view returns (bytes32)"
];
